### ISSUE TITLE
having issues trying to link a repo with subfolders

### ISSUE THREAD

**Issue by junguler** [gtalarico/markdown.is#13]
hi, i can't seem to link one of the markdown files within a subfolder in one of my repos, no matter what i do the link is not set correctly

![repo tree issue](https://user-images.githubusercontent.com/59083599/135752833-1aca742a-d731-4c59-8148-4c9f0f9da6f0.jpg)

it should be like this
https://github.com/junguler/_image-manipulation/blob/main/Triangle/README.md
but it shows it like this
https://github.com/junguler/_image-manipulation/Triangle/blob/main/README.md
which breaks the link

i read up on the documentation and manually changed the link to https://markdown.is/gh/junguler/_image-manipulation/Triangle but it didn't show the page either

sorry if i'm missing something obvious.

**Comment by gtalarico** [comment]
On Repo selector should just be repo name.
I think they trick here is to make sure you use relative paths. So in your README you should use `/file.md` or `#heading` or `Triangle/README.md#heading`

I will try to get this work interactively when I get a chance

**Comment by junguler** [comment]
thank you for the explanation, also sorry for the double issue back to back.
