### ISSUE TITLE
media embedded to the README.md of repo doesn't show

### ISSUE THREAD

**Issue by junguler** [gtalarico/markdown.is#6]
hi, cool project, it has the potential to be great, i was testing one of my repos and i realized media i have embedded directly to the markdown files does not show in the page, i had some issues with videos not showing in my markdown files so i opted to embed them directly to my markdown file in addition to uploading into the repo.

my original repo page
https://github.com/junguler/gmic-examples/blob/main/README.md
markdown-is result
https://markdown.is/gh/junguler/gmic-examples

also quick links seems to take me back to my repo instead of being a shortcut in the page

**Comment by gtalarico** [comment]
Added a fix for videos
![image](https://user-images.githubusercontent.com/9513968/135740453-607d79c5-4d00-43a5-8b55-2d0771d1e1d0.png)

As for link, we will need to do go over `<a>` tags to convert absolute github paths into relative. will open another issue for this

**Comment by junguler** [comment]
amazing work, thank you.
